const elemTranslation = [
  document.querySelectorAll(".link")[0],
  document.querySelectorAll(".link")[1],
  document.querySelectorAll(".link")[2],
  document.querySelectorAll(".link")[3],
  document.querySelectorAll(".link")[4],
  document.querySelectorAll(".link")[5],
  document.querySelector(".hero__title"),
  document.querySelector(".hero__subtitle"),
  document.querySelectorAll(".title")[0],
  document.querySelectorAll(".title")[1],
  document.querySelectorAll(".title")[2],
  document.querySelectorAll(".title")[3],
  document.querySelectorAll(".title")[4],
  document.querySelectorAll(".title")[5],
  document.querySelectorAll(".about-me__paragraph")[0],
  document.querySelectorAll(".about-me__paragraph")[1],
  document.querySelectorAll(".projects__subtitle")[0],
  document.querySelectorAll(".projects__subtitle")[1],
  document.querySelectorAll(".projects__subtitle")[2],
  document.querySelectorAll(".projects__subtitle")[3],
  document.querySelectorAll(".projects__subtitle")[4],
  document.querySelectorAll(".projects__subtitle")[5],
  document.querySelectorAll(".projects__text")[0],
  document.querySelectorAll(".projects__text")[1],
  document.querySelectorAll(".projects__text")[2],
  document.querySelectorAll(".projects__text")[3],
  document.querySelectorAll(".projects__text")[4],
  document.querySelectorAll(".projects__text")[5],
  document.querySelectorAll(".projects__link")[0],
  document.querySelectorAll(".projects__link")[1],
  document.querySelectorAll(".projects__link")[2],
  document.querySelectorAll(".projects__link")[3],
  document.querySelectorAll(".projects__link")[4],
  document.querySelectorAll(".projects__link")[5],
  document.body.getElementsByTagName("th")[0],
  document.body.getElementsByTagName("th")[1],
  document.body.getElementsByTagName("th")[2],
  document.body.getElementsByTagName("th")[3],
  document.body.getElementsByTagName("td")[0],
  document.body.getElementsByTagName("td")[2],
  document.body.getElementsByTagName("td")[4],
  document.body.getElementsByTagName("td")[6],
  document.body.getElementsByTagName("td")[8],
  document.body.getElementsByTagName("td")[10],
  document.body.getElementsByTagName("td")[11],
  document.body.getElementsByTagName("td")[12],
  document.body.getElementsByTagName("td")[13],
  document.body.getElementsByTagName("td")[14],
  document.body.getElementsByTagName("td")[15],
];

const rusTranslation = [
  "Обо мне",
  "Навыки",
  "Код",
  "Проекты",
  "Образование",
  "Контакт",
  "Привет, я Алекс!",
  "Приятно познакомится",
  "Обо мне",
  "Навыки",
  "Код",
  "Проекты",
  "Образование",
  "Контакт",
  "Я изучаю программирование пару лет. Изначально я учил Python, но во время обучения я открыл для себя веб-разработку и нашел эту область гораздо более привлекательной. В результате я переключил свое внимание на фронтенд-разработку.",
  "Помимо программирования, мне нравится смотреть аниме, читать мангу, играть в компьютерные игры (например, Factorio), играть на гитаре и слушать рок-музыку.",
  "Игра Git",
  "Игра на память",
  "Приют",
  "Бруклинская библиотека",
  "Аудиоплеер",
  "Галлерея",
  "Игра на знание Гит и Гитхаб",
  "Игра на внимательность и память",
  "Сайт приюта для животных",
  "Бруклинская публичная библиотека",
  "Пользовательский аудиоплеер",
  "сайт с Api с поиском изображений по запросу",
  "Показать",
  "Показать",
  "Показать",
  "Показать",
  "Показать",
  "Показать",
  "Заведение",
  "Год",
  "Язык",
  "Уровень",
  "Гимназия",
  "Университет магистр религиоведения",
  "Курсы по Python",
  "Курсы по веб-разработке",
  "Английский",
  "Французский",
  "Начальный",
  "Японский",
  "Начальный",
  "Татарский",
  "Начальный",
];

const englTranslatoon = [
  "About me",
  "Skils",
  "Code",
  "Project",
  "Education",
  "Contact",
  "Hello, I'm Alex!",
  "Nice to meet you",
  "About me",
  "Skills",
  "Code",
  "Projects",
  "Education",
  "Contact",
  "I’ve been studying programming for several years. I started with Python, but during my learning journey, I discovered web development and found this field much more appealing. As a result, I shifted my focus to frontend development.",
  "Beyond programming, I enjoy watching anime, reading manga, playing PC games (like Factorio), playing guitar, and listening to rock music.",
  "Git Game",
  "Memory Game",
  "Shelter",
  "Libary",
  "audio",
  "Gallery",
  "Git and GitHub knowledge game",
  "Game for attentiveness and memory",
  "Nursery website",
  "Brooklyn Public Library",
  "Custom audio player",
  "Site with an API for searching images on request",
  "Show",
  "Show",
  "Show",
  "Show",
  "Show",
  "Show",
  "Institution",
  "Institution",
  "Language",
  "level",
  "ГимнGymnasium",
  "University. Speciality - Master of Religious Science",
  "Python courses",
  "Web Development Courses",
  "English",
  "French",
  "Elementary",
  "Japanese",
  "Elementary",
  "Tatar",
  "Elementary",
];

const navTransl = document.querySelector(".nav__transl");
const selectValue = navTransl.value;
console.log(selectValue);

const translat = (dictionary) => {
  elemTranslation.forEach((element, index) => {
    element.textContent = dictionary[index];
  });
};

navTransl.addEventListener("change", () =>
  navTransl.value === "ru"
    ? translat(rusTranslation)
    : translat(englTranslatoon)
);
